doctrine:
    dbal: { connections: { default: { host: processmanager, port: 3306, user: pimcore, password: pimcore, dbname: pimcore, mapping_types: { enum: string, bit: boolean }, server_version: 8.0.29 } } }
